#!/bin/bash

# Borrowed from grunt-cli
# http://gruntjs.com/
#
# Copyright (c) 2012 Tyler Kellen, contributors
# Licensed under the MIT license.
# https://github.com/gruntjs/grunt/blob/master/LICENSE-MIT

# Usage:
#
# To enable bash <tab> completion for gulp, add the following line (minus the
# leading #, which is the bash comment character) to your ~/.bashrc file:
#
# eval "$(gulp --completion=bash)"

# Enable bash autocompletion.
function _gulp_completions() {
  # Grab tasks...
  local compls
  local cache_filepath=/tmp/gulp_completion_cache_$(pwd | sha1sum | cut -d' ' -f1)
  if [ -f $cache_filepath ] && [ $(stat -c %Y ./gulpfile.js) -lt $(stat -c %Y $cache_filepath) ]
  then
    # From cache file.
    compls=$(cat $cache_filepath)
  else
    # From gulp.
    compls=$(gulp --tasks-simple)
    echo $compls > $cache_filepath
  fi

  # The currently-being-completed word.
  local cur="${COMP_WORDS[COMP_CWORD]}"

  # Tell complete what stuff to show.
  COMPREPLY=($(compgen -W "$compls" -- "$cur"))
}

complete -o default -F _gulp_completions gulp
